apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2 # Number of pods to create
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: us-west2-docker.pkg.dev/service-project-dev-1a/my-repository/backend:latest
        ports:
        - containerPort: 9000
