apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2 # Number of pods to create
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: my-app-image
        ports:
        - containerPort: 8080
