name: GKE CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: service-project-dev-1a
  GAR_LOCATION: us-west2
  REGION: us-west2
  DOCKER_REPO: my-repository

jobs:
  build-and-deploy:
    # Add "id-token" with the intended permissions
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      # Step 2: Authenticate to Google Cloud using Workload Identity Federation
      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/89346032191/locations/global/workloadIdentityPools/github-actions-cloud-run/providers/github'
          service_account: 'github-cloud-deploy-sa@service-project-dev-1a.iam.gserviceaccount.com'
          token_format: 'access_token'

      # Step 3: Set up Google Cloud SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ env.PROJECT_ID }}'
      
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Docker auth'
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
      #    gcloud artifacts docker images list us-west2-docker.pkg.dev/service-project-dev-1a/my-repository

      # Step 4: Build and push hello image
      - name: 'Build and push Docker image for hello service'
        run: |
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_REPO }}/hello" ./hello
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_REPO }}/hello"
        # docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_REPO }}/hello:${{ github.sha }}" ./hello
        # docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_REPO }}/hello:${{ github.sha }}"

      - name: 'Create release name for hello service'
        run: |-
         echo "RELEASE_NAME=hello-${GITHUB_SHA::7}-${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}

      - name: 'Create Cloud Deploy release for hello service'
        uses: 'google-github-actions/create-cloud-deploy-release@v0'
        with:
         delivery_pipeline: 'simple-node-server-pipeline'
         name: '${{ env.RELEASE_NAME }}'
         region: '${{ env.REGION }}'
         description: '${{ env.GITHUB_COMMIT_MSG }}'
         skaffold_file: 'config/skaffold.yaml'
         images: 'app=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_REPO }}/hello:LATEST'
      #   images: 'app=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_REPO }}/hello:${{ github.sha }}'
      
      # Step 4: Set up Docker Buildx for multi-platform builds
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # # Step 5: Build and push Docker images for each service
      # - name: Build and push auth image
      #   run: |
      #     docker buildx build --load --platform linux/amd64,linux/arm64 -t auth .
      #     docker tag auth: latest ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/auth:latest
      #     docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/auth:latest

      # - name: Build and push hello image
      #   run: |
      #     docker buildx build --load --platform linux/amd64,linux/arm64 -t hello .
      #     docker tag hello: latest ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/hello:latest
      #     docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/hello:latest

      # - name: Build and push backend image
      #   run: |
      #     docker buildx build --load --platform linux/amd64,linux/arm64 -t backend .
      #     docker tag backend: latest ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/backend:latest
      #     docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/backend:latest

      # # Step 6: Deploy to GKE
      # - name: Deploy to GKE
      #   run: |
      #     kubectl apply -f ./auth/k8s/deployment.yaml
      #     kubectl apply -f ./auth/k8s/service.yaml
      #     kubectl apply -f ./hello/k8s/deployment.yaml
      #     kubectl apply -f ./hello/k8s/service.yaml
      #     kubectl apply -f ./backend/k8s/deployment.yaml
      #     kubectl apply -f ./backend/k8s/service.yaml
      #     kubectl apply -f ./k8s/ingress.yaml
            